export const requestConstants = {
  GETALL_REQUEST: 'REQUEST_GETALL_REQUEST',
  GETALL_SUCCESS: 'REQUEST_GETALL_SUCCESS',
  GETALL_FAILURE: 'REQUEST_GETALL_FAILURE',

  DELETE_REQUEST: 'REQUEST_DELETE_REQUEST',
  DELETE_SUCCESS: 'REQUEST_DELETE_SUCCESS',
  DELETE_FAILURE: 'REQUEST_DELETE_FAILURE'    
};
